### ISSUE TITLE
Replace BFM with FLAME?

### ISSUE THREAD

**Issue by emlcpfx** [lhyfst/DSFNet#1]
I am really looking forward to checking out a demo for this repo. Is it possible to swap any reference of the BFM to the FLAME model, so it can be used for commercial purposes without having to pay for a $10k BFM license?

**Comment by lhyfst** [comment]
Due to the significant difference in vertex count between FLAME and BFM (~5k vs ~50k), directly transitioning to FLAME would decrease our model's performance and require more engineering efforts. Therefore, we currently have no plans to switch to FLAME in the near future.
