### ISSUE TITLE
Is the code that was used for training available? 

### ISSUE THREAD

**Issue by xhlbetter** [lhyfst/DSFNet#3]
Hi, incredible model, thank you for having released evaluation code, and my apologies if this is a dumb question, but has the training code been made available/open-sourced as well?

**Comment by lhyfst** [comment]
Hi, thank you for your interest. However, we do not plan to release the training code soon, because it relates to our other in-process works. To reimplement the training code, my suggestion is that the SADRNet codebase will be very helpful because our code is modified from it.
